"use client";

import { cn } from "@/lib/utils";

interface DocumentPreviewProps {
  title: string;
  pageCount?: number;
  isAutoGenerated?: boolean;
  content?: string;
  onDownload?: () => void;
  onPreview?: () => void;
  className?: string;
}

export function DocumentPreview({
  title,
  pageCount,
  isAutoGenerated = true,
  content,
  onDownload,
  onPreview,
  className,
}: DocumentPreviewProps) {
  return (
    <div
      className={cn(
        "overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm",
        className,
      )}
    >
      {/* File info row */}
      <div className="flex items-center gap-3 border-b border-gray-100 px-4 py-3">
        <FileIcon className="h-5 w-5 shrink-0 text-blue-400" />

        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-gray-800">{title}</p>
          {pageCount !== undefined && (
            <p className="text-xs text-gray-400">
              {/* mobile: show "Auto-generated • N Pages", desktop: show only page count */}
              <span className="sm:hidden">
                {isAutoGenerated ? `Auto-generated • ${pageCount} Page${pageCount !== 1 ? "s" : ""}` : `${pageCount} Page${pageCount !== 1 ? "s" : ""}`}
              </span>
              <span className="hidden sm:inline">
                {pageCount} Page{pageCount !== 1 ? "s" : ""}
              </span>
            </p>
          )}
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          {onDownload && (
            <button
              type="button"
              aria-label="Download document"
              onClick={onDownload}
              className="rounded-md p-1.5 text-gray-400 transition-colors hover:bg-gray-50 hover:text-gray-600"
            >
              <DownloadIcon className="h-4 w-4" />
            </button>
          )}
          {onPreview && (
            <button
              type="button"
              aria-label="Preview document"
              onClick={onPreview}
              className="rounded-md p-1.5 text-gray-400 transition-colors hover:bg-gray-50 hover:text-gray-600"
            >
              <EyeIcon className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>

      {/* Letter preview area */}
      <div className="relative h-56 overflow-hidden bg-gray-50 sm:h-72">
        {content ? (
          <div className="h-full overflow-y-auto px-6 py-5">
            <div className="prose prose-sm max-w-none whitespace-pre-wrap text-xs text-gray-700">
              {content}
            </div>
          </div>
        ) : (
          /* Placeholder preview */
          <div className="flex h-full flex-col items-center justify-center">
            <span className="text-sm font-light tracking-[0.3em] text-gray-300 uppercase">
              Cover letter
            </span>
          </div>
        )}

        {/* Subtle gradient overlay at bottom when content is present */}
        {content && (
          <div className="pointer-events-none absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-gray-50 to-transparent" />
        )}
      </div>
    </div>
  );
}

// ─── Icon components ──────────────────────────────────────────

function FileIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      className={className}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z"
      />
    </svg>
  );
}

function DownloadIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      className={className}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3"
      />
    </svg>
  );
}

function EyeIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      className={className}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z"
      />
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
      />
    </svg>
  );
}
